check mr exists before open or merge

diff --git a/bin/mr-merge b/bin/mr-merge
--- a/bin/mr-merge
+++ b/bin/mr-merge
@@ -55,7 +55,106 @@ done
 shift $((OPTIND -1))
 
 ################################################################################
+# Chec#!/usr/bin/env bash
+
+set -e
+
+################################################################################
+# find script location
+################################################################################
+DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+
+# [ -f "$DIR/../lib/bash.sh" ] !! make -c $DIR/.. init
+[ -f "$DIR/../lib/bash.sh" ] && source "$DIR/../lib/bash.sh"
+
+################################################################################
+# script functions
+################################################################################
+function usage() {
+    echo "Find first gitlab merge request for source branch and merge it"
+    echo
+    echo "Syntax: $0 [options]"
+    echo
+    echo "options:"
+    echo "  -h    Print this Help."
+    # echo "  -r    filter by reviewer for the merge request."
+    echo "  -s    filter by source branch for the merge request."
+    # echo "  -t    filter by target branch for the merge request."
+    echo
+}
+
+################################################################################
+# Process the input options. Add options as needed.                            #
+################################################################################
+while getopts "ha:r:s:t:" opt
+do # parse and handle option flags
+    case $opt in
+        a)
+            ASSIGNEE="${OPTARG}"
+            ;;
+        h) 
+            usage
+            exit 
+            ;;
+        r)
+            REVIEWER="${OPTARG}"
+            ;;
+        s)
+            SOURCE_BRANCH="${OPTARG}"
+            ;;
+        t)
+            TARGET_BRANCH="${OPTARG}"
+            ;;
+        \?) echo "Invalid option"; exit 1 ;;
+        :) echo "Invalid Option: -$OPTARG requires an argument"; exit 1 ;;
+    esac
+done
+shift $((OPTIND -1))
+
+################################################################################
 # Check dependencies                                                           #
+################################################################################
+has_command glab || die "Missing required: glab (https://glab.readthedocs.io/en/latest/)"
+
+if [ -z "$ASSIGNEE" ]
+then
+    # if assignee is not set use gitlab magic @me
+    ASSIGNEE="@me"
+fi
+
+if [ -z "$REVIEWER" ]
+then
+    # if assignee is not set use gitlab magic @me
+    REVIEWER="@me"
+fi
+
+if [ -z "$SOURCE_BRANCH" ]
+then
+    # if source branch is not specified assume current branch
+    SOURCE_BRANCH="$(git branch --show-current)"
+fi
+
+if [ -z "$TARGET_BRANCH" ]
+then
+    # if target branch is not specified assume development branch
+    TARGET_BRANCH="$GITLAB_DEFAULT_TARGET_BRANCH"
+fi
+
+################################################################################
+# main logic                                                                   #
+################################################################################
+result=$(glab mr list --assignee=$ASSIGNEE --per-page 1 --reviewer=$REVIEWER --source-branch $SOURCE_BRANCH --target-branch $TARGET_BRANCH)
+result="${result##*$'\n'}"
+
+mr="$(echo $result | cut -d ' ' -f 1 | cut -d '!' -f 2)"
+
+if [ "$mr" == "No" ]
+then
+    echo "$result"
+    exit 0
+fi
+
+glab mr merge $mr --yesk dependencies                                                           #
 ################################################################################
 has_command glab || die "Missing required: glab (https://glab.readthedocs.io/en/latest/)"
 
